apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort  # Use ClusterIP if only internal, LoadBalancer if on cloud
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80        # External port
      targetPort: 5000 # Flask container port
      nodePort: 30007  # Optional, specific NodePort (only works with type: NodePort)
